services:
  - type: web
    name: php-site
    env: docker
    plan: free
    buildCommand: 'docker build -t php-site .'    # Comando para construir a imagem Docker
    startCommand: 'docker run -p 10000:80 php-site'   # Comando para iniciar o contêiner
    branches:
      - main   # Escolha a branch do repositório que será usada (por exemplo, main)
